Nhà Nguyễn && Nhà Nguyễn thành lập năm 1802, niên hiệu là Việt Nam, kinh đô ở Huế, là triều đại quân chủ cuối cùng cai trị Việt Nam trong lịch sử Việt Nam từ năm 1802 đến 1945, được thành lập sau khi hoàng đế Gia Long lên ngôi năm 1802 sau khi đánh bại nhà Tây Sơn và sụp đổ hoàn toàn khi hoàng đế Bảo Đại thoái vị vào năm 1945 – tổng cộng là 143 năm.
Nhà Tây Sơn && Nhà Tây Sơn hay Vương triều Tây Sơn (thành lập năm 1788 kéo dài đến năm 1802) là triều đại được ra đời trong giai đoạn khởi nghĩa nông dân của ba anh em Tây Sơn và thành lập vương triều này trong bối cảnh tranh chấp quyền lực cuối thời Hậu Lê trong lịch sử Việt Nam. Kinh đô ở Phú Xuân (Huế) và Phượng Hoàng trung đô (Vinh).
Nhà Mạc && Nhà Mạc, kinh đô Thăng Long và sau là Cao Bằng, thành lập năm 1527, là triều đại phong kiến trong lịch sử Việt Nam, bắt đầu khi vua Mạc Thái Tổ lên ngôi tháng 6 năm 1527 sau khi giành được quyền lực từ tay vua Lê Cung Hoàng nhà Hậu Lê và chấm dứt khi vua Mạc Mậu Hợp, bị quân đội Lê-Trịnh do Trịnh Tùng chỉ huy đánh bại vào cuối năm 1592 – tổng cộng là gần 66 năm.
Nhà Hậu Lê && Nhà Hậu Lê(thời Lê Sơ), quốc hiệu Đại Việt, kinh đô Đông Kinh (Hà Nội), bắt đầu thành lập từ năm 1427 và kết thúc năm 1789 là một triều đại phong kiến Việt Nam, tồn tại sau thời Bắc thuộc lần 4 và đồng thời với nhà Mạc, nhà Tây Sơn trong một thời gian, trước nhà Nguyễn.
Nhà Lê Sơ && Nhà Hậu Lê(thời Lê Sơ), quốc hiệu Đại Việt, kinh đô Đông Kinh (Hà Nội), bắt đầu thành lập từ năm 1427 và kết thúc năm 1789 là một triều đại phong kiến Việt Nam, tồn tại sau thời Bắc thuộc lần 4 và đồng thời với nhà Mạc, nhà Tây Sơn trong một thời gian, trước nhà Nguyễn.
Nhà Hồ && Nhà Hồ, quốc hiệu Đại Ngu, kinh đô Tây Đô, là triều đại phong kiến trong lịch sử Việt Nam, bắt đầu thành lập khi Hồ Quý Ly lên ngôi năm 1400 sau khi giành được quyền lực từ tay nhà Trần và chấm dứt khi Hồ Hán Thương bị quân Minh bắt vào năm 1407 – tổng cộng là 7 năm. Quốc hiệu Đại Việt đã đổi thành Đại Ngu năm 1400.
Nhà Trần && Nhà Trần, quốc hiệu Đại Việt, kinh đô Thăng Long, là triều đại phong kiến trong lịch sử Việt Nam, bắt đầu thành lập khi vua Thái Tông lên ngôi năm 1225, trải qua 12 triều vua và chấm dứt khi vua Thiếu Đế, khi đó mới có 5 tuổi bị ép thoái vị vào năm 1400 để nhường ngôi cho ông ngoại là Hồ Quý Ly - tức Lê Quý Ly – tổng cộng là 175 năm.
Nhà Lý && Nhà Lý, quốc hiệu Đại Việt, kinh đô Thăng Long, còn được gọi là nhà Hậu Lý (để phân biệt với nhà Tiền Lý của Lý Nam Đế), là một triều đại phong kiến trong lịch sử Việt Nam. Triều đại này bắt đầu thành lập khi vua Thái Tổ lên ngôi tháng 10 âm lịch năm 1009, sau khi giành được quyền lực từ tay nhà Tiền Lê, trải qua 9 triều vua và chấm dứt khi vua Lý Chiêu Hoàng, lúc đó mới có 7 tuổi bị ép thoái vị để nhường ngôi cho chồng là Trần Cảnh vào năm 1225 – tổng cộng là 216 năm.
Nhà Đinh && Nhà Đinh, quốc hiệu Đại Cồ Việt, kinh đô Hoa Lư, là triều đại phong kiến trong lịch sử Việt Nam bắt đầu thành lập năm 968, sau khi Đinh Tiên Hoàng dẹp xong loạn 12 sứ quân thống nhất đất nước và kết thúc năm 980 khi con của Đinh Tiên Hoàng là Đinh Phế Đế nhường ngôi cho Lê Hoàn.
Nhà Tiền Lê && Nhà Tiền Lê là một triều đại trong lịch sử Việt Nam, bắt đầu thành lập khi Đinh Phế Đế nhường ngôi cho Lê Hoàn vào năm 980, trải qua ba đời vua và chấm dứt khi Lê Ngọa Triều qua đời, và hoàng tử kế vị đang còn nhỏ tuổi. Quốc hiệu vẫn là Đại Cồ Việt. Là triều đại tiếp sau nhà Đinh.
Nhà Ngô && Nhà Ngô, kinh đô Cổ Loa, là một triều đại trong lịch sử Việt Nam, truyền được hai đời nhưng có tới ba vị vua, bắt đầu thành lập từ năm 939 kéo dài đến năm 965. Khoảng thời gian xen giữa từ 944 đến 950 còn có Dương Bình Vương tức Dương Tam Kha.
